import express from "express";
import { createServer as createViteServer } from "vite";
import path from "path";
import { fileURLToPath } from "url";
import { scrapePage } from "./scraper.js";

// ESM-safe __dirname
const __dirname = path.dirname(fileURLToPath(import.meta.url));

async function startServer() {
  const app = express();
  const PORT = Number(process.env.PORT) || 3000;

  app.use(express.json());

  // -----------------------------------------------------------------------
  // Static: serve screenshots generated by the Python scraper
  // -----------------------------------------------------------------------
  const screenshotsDir = path.resolve(__dirname, "./public/screenshots");
  app.use("/screenshots", express.static(screenshotsDir));

  // -----------------------------------------------------------------------
  // API routes
  // -----------------------------------------------------------------------
  app.get("/api/health", (_req: express.Request, res: express.Response) => {
    res.json({ status: "ok" });
  });

  app.post("/api/audit", async (req: express.Request, res: express.Response) => {
    const { url } = req.body as { url?: string };

    if (!url || !url.trim()) {
      return res.status(400).json({ error: "URL is required" });
    }

    try {
      console.log(`[server] Auditing: ${url}`);
      const scrapeResult = await scrapePage(url.trim());
      res.json({ status: "success", data: scrapeResult });
    } catch (error: any) {
      console.error("[server] Audit failed:", error?.message ?? error);
      res
        .status(500)
        .json({ error: "Failed to scrape page", details: error?.message ?? String(error) });
    }
  });

  // -----------------------------------------------------------------------
  // Dev: Vite middleware  |  Prod: serve built dist
  // -----------------------------------------------------------------------
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(__dirname, "dist");
    app.use(express.static(distPath));
    app.get("*", (_req: express.Request, res: express.Response) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`\n🚀  FunnelVision server → http://localhost:${PORT}\n`);
  });
}

startServer().catch((err: any) => {
  console.error("Server startup failed:", err);
  process.exit(1);
});
